development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: little_pooper_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: little_pooper_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: little_pooper_rails
  pool: 5
  timeout: 5000