# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf7c720ac352b119d60a7a28df4c27aba9b732fe9b2d500bb3b905f2cd38976570043288166266f7e821e2da9c63c216487f6de84525ebc331d72f6d03c3d7e6
  client_id: 988364238506-qp70i2078v0s0qb630ef9cud3sqbnndn.apps.googleusercontent.com
  client_secret: 0ZciakHIh5ktYYuLUxu9TiOX
  state: SecureRandom.hex

test:
  secret_key_base: 246803ea6af88f891b8d972b5761f9d9a3d1ca7c37a291eb7580f6483de5d59554436d1c7b34b0dd6019cab6477233dcf63c34e5ac638058d51f82f56d07e8af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
